### ISSUE TITLE
Add entry point for automated testing

### ISSUE THREAD

**Issue by porst17** [hilbert/hilbert-cli#1]
I would like to add automated (unit) testing to the project and need an entry point for it, e.g. `make test`. Non-zero exit codes indicate a failed test.

Once basic automated testing is in place, we can start adding test cases.

**Comment by malex984** [comment]
`.travis.yml` is already available. It uses `tox`. 

`make check` may also be used during development.

**Comment by malex984** [comment]
this functionality was introduced by PR merge: b9c50315c42024483e6356f5fba37d77018c1a64
and finally fixed with 5b3df8fa9d70cd31a5c16c969c59294f1b108fff
