### ISSUE TITLE
Do wake-on-lan call via another docker image OR install WOL within Management image?

### ISSUE THREAD

**Issue by malex984** [hilbert/hilbert-cli#11]

**Comment by porst17** [comment]
Is there any argument against putting the WOL tool into the management image? If not, wouldn't this be the simplest solution?

**Comment by malex984** [comment]
> Is there any argument against putting the WOL tool into the management image?
 
not really, it only requires access to host network.

> If not, wouldn't this be the simplest solution?
 
yes, it is.

**Comment by porst17** [comment]
By 

> requires access to host network

, do you mean `docker run --network host`?
If yes, why is this necessary?

**Comment by malex984** [comment]
>  do you mean docker run --network host?

Yes. Well, with something touchy and critical like WOL i would like to avoid any intermediate layers that possibly can get into the way...

TODO: test WOL from within a docker container running with different networking modes: host & bridge  (see https://docs.docker.com/engine/userguide/networking/)

**Comment by porst17** [comment]
Which tool are you using for WOL?

**Comment by malex984** [comment]
Ubuntu Package Info with some minor added bits:

```
Package: wakeonlan                       
Version: 0.41-11 ($Id: wakeonlan,v 1.4.2.3 2005/01/27 16:03:54 jpo Exp $)
Section: net
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> (Originally by Jose Pedro Oliveira)
Architecture: all
Uncompressed Size: 57,3 k
Depends: perl, perl-modules
Description: Sends 'magic packets' to wake-on-LAN enabled ethernet adapters  and motherboards, in order to switch on the called PC. The 'magic packet' consists of 6 times 0xFF followed by 16 times the hardware address of the NIC. This sequence can be encapsulated in any kind of packet. This script uses UDP packets.
```

**Comment by malex984** [comment]
According to (#42): running short-lived tasks via special purpose docker images does not fit with our execution model. 

In the current implementation of Hilbert server-side tool (see class `WOL`) - `wakeonlan` is executed directly => it should be added to the same management image as the tool. Same goes to other executed tools.
