### ISSUE TITLE
Configuration design: Use of YAML Anchors/aliases

### ISSUE THREAD

**Issue by malex984** [hilbert/hilbert-cli#16]
Note: this is a separation of super-issue hilbert/hilbert-cli#13

**Eric said:**

**General: 1.1:** Yes, anchors seem to be used wrong. I wouldn't use them at all... a simple / plain config is enough and it's not really necessary, nor useful if it makes it more verbose instead of less (which is the intent of anchors).

**Profile: 3.5** Use strings instead of anchors for apps and services.

**Comment by porst17** [comment]
I also suggest to avoid anchors in the configuration format and rely on (string) IDs instead that we can handle explicitly when parsing the config. Anchors are valid YAML, so the user is free to avoid certain repetitions on his own if necessary.

If an anchor is defined more then once, the later definition would overwrite the first, which is common practice in most config formats (e.g. you have a default config and overwrite certain values by defining things).

**Comment by malex984** [comment]
What follows is migration from the super issue #13:

>    _1.1:_ Yes, anchors seem to be used wrong.

**Alex**: 
Updated in https://gist.github.com/malex984/59d2b62c5098eb1005100f9249719505#file-all_flat_update-yml

**Eric:**
They're a bit of a nightmare now. Resolving references should be done in our code, not in the YAML parser. In your example you described the apps and created an anchor for each and then on the description of the station you used those anchors. 
- This means that when you're parsing the description of the stations you'll receive the full config of each app in each station instead of just the ID. This is at best useless repetition...
- ... and at worst dangerous, because YAML doesn't know IDs are IDs (non-repeatable) so it'd be possible to create a config where an app is described twice with the same ID but different values, once through an anchor and the other explicitly, with no way of figuring out they're different except comparing them all.

Anchors can be used by the user to avoid writing the same value many times in the cfg, like a convenient macro... but we shouldn't use it as a structural / organizational element of the config. Also, there's no equivalent in JSON or INIs.

>    I wouldn't use them at all... a simple / plain config is enough and
>    it's not really necessary, nor useful if it makes it more verbose instead
>    of less (which is the intent of anchors).

**Alex**:  
If we choose to use YAML - better use it fully: as far as i understand
anchors and aliases provide safe (automatically verifiable)
cross-references to very often used data.

**Alex**:
Say, if we have some (non-trivial) Profile for ~100 Stations - i would not
want to embed its definition directly into all those stations definitions.

**Eric:**
But this is exactly what you're doing with the anchors. We can reference the profile with a name/id and describe it elsewhere and this is resolved very easily in our program.

**Comment by malex984** [comment]
**Alex:**

@Eric, sorry but I disagree with you on anchors: i noticed no total embedding according to following sample for Python2 with PyYAML & ruamel (see also  http://pyyaml.org/wiki/PyYAMLDocumentation#Aliases):

```
import yaml
class KV:
    def __init__(self, v):
        self.k = v

a = KV(1)
b = KV(2)
P = { 1: [a, b], 2: [a], 3: [b] }
print yaml.dump(P)
# 1:
# - &id001 !!python/object:__main__.KV {k: 1}
# - &id002 !!python/object:__main__.KV {k: 2}
# 2:
# - *id001
# 3:
# - *id002
d =  """1:
- &id001 !!python/object:__main__.KV {k: 111}
- &id002 !!python/object:__main__.KV {k: 222}
2:
- *id001
3:
- *id002
"""
y = yaml.load(d)
print y
# {1: [<__main__.KV instance at 0x7f60c6925170>, <__main__.KV instance at 0x7f60c6925200>], 2: [<__main__.KV instance at 0x7f60c6925170>], 3: [<__main__.KV instance at 0x7f60c6925200>]}
(y[1][0] == y[2][0]) and (y[1][1] == y[3][0]) and (y[2][0] != y[3][0]) and (yaml.dump(y) == d)
# True
```

Please also consider the following perfectly valid YAML: `&A [ *A ]`!

Therefore, for me aliases are exactly **cross-references** that can serve as unique **ID**s, provided one would not introduce multiple identical anchors by mistake, which can be detected during loading/parsing... but the situation is identical with using strings as IDs for (loose) references - which looks like re-inventing cross-references where they are already available...

@Eric, could it be that you think about JSON instead of YAML?

**Comment by malex984** [comment]
**Eric:** 

The fact that we have to send each other code samples to show how the parser interprets the file **should** be enough to make it clear that this feature isn't obvious enough to be used in cfg. The cfg should be obvious to the user.

However...

```
import yaml

cfg_file = """
people:
  alice: &alice {name: 'Alice Anderson', age: 29, email: 'alice@example.com'}
  john: &john {name: 'John Jameson', age: 30, email: 'john@example.com'}
  peter: &peter {name: 'Peter Parker', age: 25, email: 'peter@example.com'}
teams:
  alpha: [*john, *peter]
  beta: [*peter, {name: 'Green Goblin', age: 60, email: 'hacker@example.com'}]
  gamma: [*john, {name: 'Peter Parker', age: 85, email: 'peter@example.com'}]
"""

cfg = yaml.load(cfg_file)

print cfg.get('teams')['alpha']
# output:
# [{'age': 30, 'name': 'John Jameson', 'email': 'john@example.com'},
# {'age': 25, 'name': 'Peter Parker', 'email': 'peter@example.com'}]

print cfg.get('teams')['beta']
# output:
# [{'age': 25, 'name': 'Peter Parker', 'email': 'peter@example.com'},
# {'age': 60, 'name': 'Green Goblin', 'email': 'hacker@example.com'}]

print cfg.get('teams')['gamma']
# [{'age': 30, 'name': 'John Jameson', 'email': 'john@example.com'}, 
# {'age': 85, 'name': 'Peter Parker', 'email': 'peter@example.com'}]
```

Notice the **Green Goblin** was added to team **beta** and when we do `cfg.get('teams')['beta']` it looks JUST like Peter Parker, which is a valid user that exists in the "people" table. So if I validate the teams table it looks like everything is OK, but the user did something illegal.

So how can I validate? Suppose I check that every user in a team is also on the **people** table... I could do that... but consider team **gamma** where I added a Peter Parker with the wrong age... so to pick that error in the cfg I would have to compare EVERY FIELD of each person to make sure **teams** and **people** are consistent.

Something else: Notice that on the **people** table I indexed each member with an ID that's non repeatable, because **people** is a map. If I repeat an ID the parser will overwrite the former occurrence with the latter... just like would happen on an INI file if I set a value twice.

... but now the ID is not accessible on the copies of the **people** that are on the teams. If I do `cfg.get('teams')['gamma'][0]` I can't get the ID... unless I repeat the ID within the map, which is error prone, redundant, etc.

**Comment by malex984** [comment]
**Alex:**

I suppose you want to ensure that there are always unique canonical places in a config file for defining ALL possible items of the same type (e.g. Tables for "people" / "teams" etc.), where you additionally introduce (almost) unique IDs (as a primary key for those tables) for referencing from other parts - de-referencing such "ID"s you would have to do manually (i.e. know from context): whether some string is a just some a string or a reference to one of existing table. I hope i am not terribly wrong here?

Also this approach is very generic and JSON-like. I suppose one just cannot do anything else with JSON...

As a developer i am all for that approach!

But after learning YAML i tried to make most use of YAML features to enable config-writers to easily create concise definitions with as small additional overhead as possible. In particular: to eliminate that cross-reference matching (IDs are often only introduced intermediately for correct serialization/deserialization) and necessarily total globalization of all kinds of shared information.

BTW, following my proposal your sample YAML would look as follows:

```
GenerallyKnownPeople:
 - &alice !!python/object:Person { name: 'Alice Anderson', age: 29, email: 'alice@example.com'}
 - &john !!python/object:Person { name: 'John Jameson', age: 30, email: 'john@example.com'}
 - &peter !!python/object:Person { name: 'Peter Parker', age: 25, email: 'peter@example.com'}
 - &judge !!python/object:Person { name: 'Some Judge', age: 61, email: 'judge@example.com'}
.....
 - &alice !!python/object:Person { name: 'Alice Jameson', age: 29, email: 'alice2@example.com'}

teams:
 - &alpha [*john, *peter]
 - &beta [*peter, &newbie1 !!python/object:Person { name: 'Green Goblin', age: 60, email: 'hacker@example.com'}]
 - &gamma [*john, &newbie2 !!python/object:Person { name: 'Peter Parker', age: 85, email: 'peter@example.com'}]
 - &delta [*newbie1, *newbie2 ]
```

As far as i understand parser/loader would have to fail on redefining tags (therefore unique IDs!), semantic checker will complain about old team players (if there is such a rule) and warn about direct object definitions within team definition (instead of using a global alias). 
I agree that this is not an ideal solution but this is just a possible additional approach, which can be  tedious to check but also viable if user sees benefits in using it.

> Something else: Notice that on the people table I indexed each member with an ID that's non repeatable, because people is a map. If I repeat an ID the parser will overwrite the former occurrence with the latter... 

Wow, sounds **really dangerous** if that silently goes unmentioned by parser/loader due to language specification... e.g. "alice" immediately visible to a config writer is 'Alice Anderson' instead of later overwriting 'Alice Jameson'  in a potentially very long listing of people.

**Comment by malex984** [comment]
I switched to string ids. It is currently reflected in the minimal sample in Google Document
