### ISSUE TITLE
Configuration design: Service definition

### ISSUE THREAD

**Issue by malex984** [hilbert/hilbert-cli#19]
Note: this is a separation of super-issue hilbert/hilbert-cli#13

**ServicesAndApplications: 2.1** I don't understand what all the `ref: "docker-compose.yml"` are, but if they're all the same they're not needed.

**Comment by porst17** [comment]
`docker-compose.yaml` should just be the default value of `ref`. Same with all other options that rarely change and can have sensible defaults.

**Comment by malex984** [comment]
**Alex said:**

>    _2.1_ I don't understand what all the ref: "docker-compose.yml" are,
>    but if they're all the same they're not needed.

All Services (and Applications) have to be defined in some docker-compose file. Currently: https://github.com/hilbert/hilbert-cli/blob/devel/config/templates/docker-compose.yml

But this may change.

**Comment by malex984** [comment]
**Eric said:**

Yes. But if the value will always be the same then we don't need to indicate it in the cfg or it should go elsewhere where it doesn't need to be repeated. If it will be different each time then change it to make that clearer. Also consider using a default filename so it only needs to be configured if we want to override the default. If the cfg is shorter, it's better.

**Comment by malex984** [comment]
IMO: we should support different original `docker-compose.yml` files.
Updated in the old [all_flat.v0.1.0.yml](https://gist.github.com/malex984/59d2b62c5098eb1005100f9249719505#file-all_flat-v0-1-0-yml) 

**Update**: see also [mini sample](https://gist.github.com/malex984/59d2b62c5098eb1005100f9249719505#file-mini_sample-yml)

**Comment by malex984** [comment]
It is related to (#9) , (#18) , (#29).
1. the general YAML configuration needs to reference the `docker-compose.yml`-files containing low-level service/app. definitions.
2. there may be individual `docker-compose.yml`-file for each service and application.
3. service/app. definition in one `docker-compose.yml`-file may explicitly reference other `docker-compose.yml`-files in a hierarchical manner...
4. These files are required to start a service/app. via `Hilbert-CLI-Station` => they should end-up being available to the Hilbert client tool (e.g. be stored alongside with the station's local configuration).

We have 2 choices (similarly to the ssh details discussed in #25):
- EITHER they are to be obtained from CMS just like the general YAML configuration during its reloading 
- OR we might require admins to additionally update them on the Server each time another application has been added to the general YAML configuration (which looks like a very **bad design** decision IMO)

**Comment by porst17** [comment]
Again, hilbert will only pick up what is available on the management server at startup. How admins put it there is not hilbert's concern. We can assist admins by providing `hilbert sync` (+ maybe `hilbert deploy`) (see #29) but this is out of the scope of this issue.

**Comment by malex984** [comment]
# Current implementation/documentations: 

`Service` and `Application` are currently documented in the design document and implemented accordingly in `config/hilbert_cli_config.py` under the names: `ServiceWrapper` and `ApplicationWrapper`:

- `ServiceWrapper` inherits from `VariadicRecordWrapper` and supports only `type == 'compose'` leading to `DockerComposeService` Validator. Its structure is described in the Design document.

- Similary: `ApplicationWrapper` inherits from `ServiceWrapper` and supports only `type == 'compose'` leading to `DockerComposeApplication`, inheriting from `DockerComposeService`. Its structure is described in the Design document. 

Note: duplication of `ServiceID` vs `ApplicationID` will be tested within `tests/test_validate.py` via `tests/data/non_unique_app_service_ids_Hilbert.yml` (to be pushed/merged soon).

**TODO: separate unit-tests for `DockerComposeApplication` and `DockerComposeService` are missing ATM.**

# Back to the main issue topic:

External resource (specified by `DockerComposeService::file`) will be searched alongside with the main Hilbert YAML Configuration file. By default it is `docker-compose.yml`.

Note: `DockerComposeService` will expect the service/application given `DockerComposeService::ref` to be present in corresponding external docker-compose specification. Mandatory only in PEDANTIC mode!

**Comment by malex984** [comment]
Note: missing functionality / tests will be implemented within #14
