### ISSUE TITLE
Configuration design: Structure/definition of a `profile`

### ISSUE THREAD

**Issue by malex984** [hilbert/hilbert-cli#21]
Note: this is a separation of super-issue hilbert/hilbert-cli#13

**Profile: 3.3** Why do profiles need a default app? If profiles are mostly generic (e.g. "Web kiosk", "Interactive touchscreen", etc.) then they're too generic to have a specific default app, unless that app is something like just a logo, or a test screen to adjust color / brightness / sound volume. I would just keep defaults in the stations. It's not too crazy to require that the admin must configure a default app for each station least he get a black screen.

**Comment by porst17** [comment]
No default app for profiles. The main argument is that profiles are common for several machines which in turn usually have its own default app, i.e. the default would be changed for most station of the same profile.

If you really need at least some application running for monitoring purposes, you could create a dummy application named `hilbert-none` or so and that is distributed with hilbert and sends heartbeats but doesn't provide a UI. This app would always run if nothing else is specified for a station. The monitoring system could issue a warning (not an error) if it sees `hilbert-none` running on a station.

**Comment by malex984** [comment]
**Alex said:**

> - _3.3_ Why do profiles need a default app? If profiles are mostly
>   generic (e.g. "Web kiosk", "Interactive touchscreen", etc.) then they're
>   too generic to have a specific default app, unless that app is something
>   like just a logo, or a test screen to adjust color / brightness / sound
>   volume. I would just keep defaults in the stations. It's not too crazy to
>   require that the admin must configure a default app for each station least
>   he get a black screen.

It seems that we lack a common definition of a Profile :-(
Therefore i stick to what i gathered from our meetings with the clients:
my understanding of Profiles is more like "Interactive stations in the same
specified location" (e.g. "InteractivesOnFloor1", "InteractivesInTestRoom",
"InfoScreensAtEntranceHall")

IMO having default application in a profile makes it easier to change the
default GUI application for the whole group of stations (provided they do
not override that default),
e.g. update GUIApp_v1 -> GUIApp_v2  for all InfoScreens in a testing room.

Also it simplifies initial creation of new station definitions.

**Comment by malex984** [comment]
**Eric said:**

> It seems that we lack a common definition of a Profile :-(
> Therefore i stick to what i gathered from our meetings with the clients:
> my understanding of Profiles is more like "Interactive stations in the same
> specified location" (e.g. "InteractivesOnFloor1", "InteractivesInTestRoom",
> "InfoScreensAtEntranceHall")

They physical location and the software running on it are completely different concerns. We can use tags for physical locations, but tags are very lightweight identifiers that can be configured through a single field or even using the frontend.

... So far I understood the profile was the type of station (touch screen interactive, projector, dome projector, non interactive screen, kinect, etc.)

> IMO having default application in a profile makes it easier to change the default GUI application for the whole group of stations (provided they do not override that default), e.g. update GUIApp_v1 -> GUIApp_v2  for all InfoScreens in a testing room.
> Also it simplifies initial creation of new station definitions.

If Touch screen interactive stations run 5 different apps then having a default one in the cfg doesn't make it any easier to change the assignment because you only affect 1/5th of those... and you'd be configuring 4/5ths explicitly and 1/5th implicitly... which is messy. We should use the front end, and presets, to make it easier / faster to assign apps to stations.

**Comment by malex984** [comment]
1. Currently stations' **profile only specifies the sequence of background services that should run on corresponding stations** and has no direct connection with Applications
2. But ProfileIDs may be used as **GroupID**s due to (#15).
3. Stations that are compatible with multiple applications **must** specify one of them via **`default_application: AppID`** (otherwise it is an error).

Most recent minimal YAML sample is at https://gist.github.com/malex984/59d2b62c5098eb1005100f9249719505#file-mini_sample-yml

**Comment by porst17** [comment]
I suggest to deprecate `default_application` once presets (#30) are in place. They provide a universal and cleaner approach to specify which applications to run on which station.

**Comment by malex984** [comment]
@porst17 Not clear to me: 
1. AFAIU presets are supposed to be only used by Dashboard to **switch** between compatible applications (specified by an active general configuration) on some hosts **in one go** (otherwise they would essentially define a totally different general configuration rather than a light run-time addition to one)... 
2. switching applications is supposed to be a **temporary** change that goes away after reboot
3. `default_application` specifies which application runs on a station by default if there is no management from outside (i.e. in standalone use case). It will be a part of local station configuration (for `Hilbert-CLI-Station`) alongside with `services` (and maybe `compatibleApplications` - e.g. for pre-loading all possibly necessary docker images in order to speed up the app. switching later on)

**Comment by porst17** [comment]
If `hilbert-cli` would support presets, there could be one preset `default` that is just used by default. `hilbert-ui` would then just forward the request to switch to a certain ~~profile~~ preset to `hilbert-cli`. After switching to some ~~profile~~ preset, going back to the defaults would just be another ~~profile~~ preset switch. No need to add another code path for `default_application`. IMO this would be a cleaner software design.

But let us not discuss this now, but rather when time has come to implement presets.

**EDIT:** Changed _profile_ to _preset_.

**Comment by malex984** [comment]
I agree: it would be better to have some presets (including some `default` one) on CMS for the general YAML config and specify `default_application` for each stations therein. Then switching **`preset`** (not _profile_) may be a part of `Hilbert-CLI-Server` but AFAIR @elondaits wanted them to be completely handled by Dashboard... ?

**Comment by porst17** [comment]
Changed `profile` to `preset` in https://github.com/hilbert/hilbert-cli/issues/21#issuecomment-257276727.

**Comment by porst17** [comment]
Could you please stop talking about _CMS_? This is a very specific requirement for **one** installation of hilbert. From the perspective of `hilbert-cli`, the _CMS does not exist_. Loading configuration data from another server is a separate process that may at best be triggered via hilbert.

Also, `default_application` in `Station` can be kept until we are actually working on the presets. Deprecating `default_application` in `Station` in favor of presets is no problem since it will still happen before the first stable release of `hilbert-cli`, I guess.

**Comment by malex984** [comment]
IMO we can postpone discussion on **presets** if they are
- **NOT** part of the general YAML config file
- **NOT** referenced by the general YAML config file
- **ONLY** handled by the Dashboard

Otherwise we have to decide at least on one of the following:
- how to put several presets into the general YAML config file:

```
Presets:
  default_preset: { ... }
  test_preset: { ... }
```

NOTE: In this case the precise **presets** definition and configuration may be discussed later...
- how to put them as external resources, for example:

```
<PATH>/HILBERT.YAML # general config file
<PATH>/services_and_applications/docker-compose.yml # files referenced by Services&Apps.
...
<PATH>/presets/default.yml # Preset definitions, may be NOT referenced directly by the general config file...?
<PATH>/presets/event1.yml # for some special event or occasion
...
```

NOTE: In this case **presets** may be postponed to next phase: "Hilbert-CLI Design" (see #14 or hilbert/hilbert-docker-images#28). See also #29, #18.

**Comment by porst17** [comment]
Presets may become part of the YAML config or may be separate. I don't know yet.

I don't see why presets can't be added in a backwards compatible way to the cli and the config. If you have good arguments, I would be interested. (Except that `default_application` in `Station` may be deprecated.)

Also, **this issue was about profiles**. Therefore, I am not going to discuss **presets** any further in this issue. The fact that I made a typing error in https://github.com/hilbert/hilbert-cli/issues/21#issuecomment-257276727 mixing presets and profiles doesn't change that.

**Comment by malex984** [comment]
It is now clear that `default_application` is actually a setting for `Hilbert-CLI-Station`.

I am going to make it a part of **`StationSettings`**, e.g. `hilbert_station_default_application`. Ok?

**Comment by elondaits** [comment]
I looked at the **Management back-end** document and can't find any mentions of StationSettings or hilbert_station_default_applications. There aren't any in the [file-mini_sample-yml ](https://gist.github.com/malex984/59d2b62c5098eb1005100f9249719505#file-mini_sample-yml) either. 

... so I think what you mean is that default_application is a property of each station's cfg, but I'm not sure.

If the station restarts (let's say it crashed)... shouldn't it restart whatever application was running before crashing instead of the "default" one? Because if it was running the configured default it's the same... and if it was told to run something else then on a crash it changes and it's probably wrong.

**Comment by porst17** [comment]
@elondaits I think @malex984 is referring to `settings` of `Station` which is of type `StationSettings` (it is only shown in the _class diagram_ of the config structure in the Management back-end document).

`setting` also might not be a good name. Because if these things are _settings_, what are the other fields in `Station` then?

**Comment by elondaits** [comment]
Yes, I'd rather see what this means in terms of YAML structure because configs are not typed and the 1:1 relation would not be needed as there's no behavior (methods) to encapsulate. I'm not sure if the [file-mini_sample-yml ](https://gist.github.com/malex984/59d2b62c5098eb1005100f9249719505#file-mini_sample-yml) is the latest spec then.

**Comment by malex984** [comment]
Thanks @porst17 your comment https://github.com/hilbert/hilbert-cli/issues/21#issuecomment-257348490 is correct. Note: **Management back-end** document has been updated to reflect that.
Would you like `hilbert_cli_station_settings` / `hilbert_cli_station_default_settings` / `client_settings` instead of `settings`?

Update: ~~@elondaits I will update YAML samples a bit later today.~~  (see https://github.com/hilbert/hilbert-cli/issues/21#issuecomment-257471302 below)

**Comment by malex984** [comment]
> If the station restarts (let's say it crashed)... shouldn't it restart whatever application was running before crashing instead of the "default" one? Because if it was running the configured default it's the same... and if it was told to run something else then on a crash it changes and it's probably wrong.

@elondaits Valid corner case. We were told that after rebooting station should revert to the configured default, but i am not sure whether it should be the same with crashes...

**Comment by malex984** [comment]
Please consider the updated [minimal sample](https://gist.github.com/malex984/59d2b62c5098eb1005100f9249719505#file-mini_sample-yml)

**Comment by porst17** [comment]
After a crash, a station should always start the last app that was running before. In contrast, if it is restarted through hilbert, you can configure this "last app" to anything you want before shutting down, e.g. by using the default preset or some other user defined value.

**Comment by malex984** [comment]
@porst17 I created another issue to discuss crash-behavior: (#31).
IMO `Hilbert-CLI-Station` should NOT decide - if Dashboard is present.

In any case we may pre-configure some default action for `Hilbert-CLI-Station` to perform upon crash/reboot (e.g. in absence of  Dashboard for a long time?). For example `client_settings` may contain the following keys:
- `hilbert_station_default_crash_policy_timeout: int`
- `hilbert_station_default_crash_policy: string`,  to be defined in (#31),  e.g. 
  - `start_monitoring_agent`, 
  - `restore_last`, 
  - `reinitialize_default`

**Comment by malex984** [comment]
[Here](https://github.com/hilbert/hilbert-cli/issues/32#issuecomment-258640551) is a note about Profiles / Groups usage by UI.
