### ISSUE TITLE
Configuration design: Matching applications with stations (originally: via profiles)

### ISSUE THREAD

**Issue by malex984** [hilbert/hilbert-cli#22]
Note: this is a separation of super-issue hilbert/hilbert-cli#13 . See also hilbert/hilbert-cli#15 .

**Profile: 3.4** I don't think profiles should "know" about applications. That's not normally how it's done. Normally a "profile" is a dependency of an application, not the other way around. For instance: an application requires Linux, Linux doesn't have a list of applications it can run. For that reason it seems each application should instead have a list of compatible profiles it can be deployed to. If a new app is added or a new version of an app is created you simply list under what profiles it runs, and that's it.

**Comment by porst17** [comment]
I would not put the list of possible applications into the profile. Better put the possible profiles or whatever kind of dependencies we choose (see also #15 ) into the application: Stations (hardware part) and profiles (software part) change rarely, but applications change more often. Or maybe even make the associations a separate thing:

```
applications_on_profiles:
  app1: profile1
  app2: [profile1, profile2]
  [app3,app4]: [profile2, profile3]
```

While this is valid YAML, I am not sure if all parsers support complex keys like `[app3,app4]`. But this would avoid some redundancy. The name `applications_on_profiles` is also subject to discussion, but you get the idea ...

**Comment by malex984** [comment]
**Alex said:**

>    _3.4_ I don't think profiles should "know" about applications. That's
>    not normally how it's done. Normally a "profile" is a dependency of an
>    application, not the other way around. For instance: an application
>    requires Linux, Linux doesn't have a list of applications it can run. For
>    that reason it seems each application should instead have a list of
>    compatible profiles it can be deployed to. If a new app is added or a new
>    version of an app is created you simply list under what profiles it runs,
>    and that's it.

Sorry but I do not believe that there is canonical ("normal") approach which is ALWAYS best with no regard on 
- how often one manually add/change Services/Applications/Profiles/Stations and
- how complicated these operations are to perform manually!

I think you consider Profiles as Tags to be attached to Applications, correct?
I would propose to make your "normal" approach also possible (alongside with the current direct approach), e.g. by adding an optional Application filed: set of `Profile`s.

**Comment by malex984** [comment]
**Eric said:**

> Sorry but I do not believe that there is canonical ("normal") approach which is ALWAYS best with no regard on
> - how often one manually add/change Services/Applications/Profiles/Stations and
> - how complicated these operations are to perform manually!

Consider:
- Applications always "know" what they need to run (dependencies, hardware requirements)
- Systems (soft + hardware) don't "know" what applications might be run on them.

But also:
- Number of Apps > Number of Profiles (and thus apps will be added more often than profiles). Profiles should be redefined if they need to be redefined... not every time an app is added. If you add an app you CAN'T avoid adding an entry to it, but you CAN avoid modifying existing profiles.

> I think you consider Profiles as Tags to be attached to Applications, correct?
> I would propose to make your "normal" approach also possible (alongside with the current direct approach), e.g. by adding an optional Application filed: set of `Profile`s.

Not "tags", but "compatible profiles", just like the "compatible hardware / OS" requirements of any application. Making both possible does not make sense, because this configuration is used to restrict what apps can be launched on which profiles... if profiles indicate apps and apps indicate profiles you must maintain both lists manually instead of specifying one and computing the other through the program.

**Comment by malex984** [comment]
It is obsolete with #15.
