### ISSUE TITLE
Add Apache v2 license

### ISSUE THREAD

**Issue by porst17** [hilbert/hilbert-cli#28]
- [x] Add top-level [`LICENSE`](http://www.apache.org/licenses/LICENSE-2.0) file.
- [x] Add the modified license header to the `LICENSE` file ([example](https://github.com/docker/docker/blob/master/LICENSE))
- [x] Add top-level [`NOTICE`](https://www.apache.org/legal/src-headers.html#notice) file. This file is also used to specify the licenses of third-party dependencies that are distributed as part of our code (if any)
- [x] Reference both, `LICENSE` and `NOTICE`, in `README.md`.

See https://www.apache.org/legal/src-headers.html for a general discussion and FAQs.

**Comment by malex984** [comment]
Please check https://github.com/hilbert/hilbert-docker-images/pull/45

Do we need to add the contents of NOTICE (or bottom of LICENSE) to the header of each file?

**Comment by porst17** [comment]
No, it is not strictly required if it is obvious which files are subject to the license.

**Comment by malex984** [comment]
See also: 
- hilbert/hilbert-cli#38
- ~~https://github.com/hilbert/hilbert-heartbeat/pull/10~~

**Comment by malex984** [comment]
was closed with 28c39b7959d6da5ebb417368b7655e3df7461143 (PR #38 )
