### ISSUE TITLE
External hosting of configuration data, software and whatnot

### ISSUE THREAD

**Issue by porst17** [hilbert/hilbert-cli#29]
**Syncing** all data of the management server with some external source **is out of the scope of hilbert**.

It is a process of setting up a valid configuration on the management server for running hilbert before it starts up. hilbert will not pull config from anywhere. Not for itself and not for the server it is running on. It will just use what's already there. We fix the requirements for hilbert and the users/clients have to meet these requirements. If our users/clients decide to host all configuration data for hilbert and the management server on a separate machine, it is their responsibility to sync this data over to the management server upon each change and restart hilbert. That is what I understand by syncing.

The best thing we can offer **within hilbert** is to **trigger the syncing** via some method given in the already available config of hilbert (the _initial syncing is out of scope_ again). This could be a script we execute on the management server (outside of the container), e.g.

```
sync: |
  #!/bin/sh
  curl -L -s http://cms.example.com/sync-data-to-management-server.php
```

would call a script on their servers that can in turn log into our management server and does whatever is necessary (`scp`, `rsync`, scripts, ...). We would just output the value of `sync` to a temporary file on the management server, `chmod +x` it and call it.

This will work on the main and the backups servers unless the CMS url becomes invalid. But we can not foresee all possible cases. It is impossible.

The `sync` script could also be much more complex, but we as authors of hilbert do not care what it actually does.

In any case, our management server needs at least some prior knowledge of the infrastructure it is living in. Being it scripts to retrieve external resources, URLs and login credentials for the CMS the data is hosted in or whatever. As soon as relevant parts of the outside world change, our management servers need to be updated accordingly. The only thing we can do is to minimize the effort IT admins have to put into it. And I think, triggering execution of a user defined script is all we should offer.

**Comment by malex984** [comment]
For the reference:
- [brief description of Hilbert's station architecture](https://github.com/hilbert/hilbert-cli/issues/25#issuecomment-256086575)
- [brief description of the operation of Management Backends](https://github.com/hilbert/hilbert-cli/issues/25#issuecomment-256095561)

If i recall it correctly, according to our discussion in Heidelberg, Dashboard may be used (e.g. using a special Button or HTTP API) to trigger update of local configurations on all stations (including the server) upon changes to the general configuration (initially available only on the CMS). I call this procedure -**configuration synchronization**. For that `Hilbert-CLI-Server` (running within a docker container) has to go through the following steps:
1. access CMS (via a pre-configured method specified by `Hilbert-CLI-Client` local config on the server)
2. get (at least) the general configuration
3. validate it & make sure all required external resources (e.g. `docker-compose.yml`) are available 
4. use the general configuration (and required external resources) to generate new individual station configuration (that will be used by `Hilbert-CLI-Client`) for each station with installed `Hilbert-CLI-Client`
5. trigger "full stop" action on all those (accessible) stations
6. deploy individual configurations to all those stations
7. trigger post-install action (currently `prepare`) on all those stations
8. restart those stations

Note: post-install action on the server may reconfigure OMD, for instance if new hosts may need to be monitored.

IMO this is actually part of Hilbert-CLI-Station design (hilbert/hilbert-docker-images#28).

**Comment by porst17** [comment]
Hilbert should make sure that whenever it starts, it uses the most recent **local** config and does everything necessary for the remote stations to work according to this config. This might trigger a full redeploy to all stations, which is not optimal during normal operation and should be an explicit thing. So I can imagine that hilbert checks for changes in the config (checksum) whenever it has to read the config. If the changes require actions on the remote stations, hilbert refuses to continue and reports the error. An additional `hilbert deploy` (currently `prepare`) will then do the actual work. There can also be a `hilbert deploy -l` to list necessary updates (e.g. to be shown in the UI) and `hilbert op --force-deploy` where `op` is some operation that requires to read the config and might therefore block. The UI could even offer a button to re-deploy hilbert to a remote station. Just in case something is broken due to manual intervention (e.g. some admin trying to debug things).

The main point is that
- syncing configuration data, software et. al between a remote location, e.g. a CMS, and the location this data belongs to on the management server
- hilbert picking up the current local configuration
- hilbert deploying necessary data to the remote stations
  are separate things. And they should be properly separated in the code and the system design.

**Comment by porst17** [comment]
The [example configuration](https://gist.github.com/malex984/59d2b62c5098eb1005100f9249719505#file-mini_sample-yml) contains

```
Stations:
...
  supernova:
  ...
    client_settings:
      ...
      HILBERT_SERVER_SYNC_URL: "sftp://DP.CMS.ESO:hilbert" # external location of the general YAML configuration
      HILBERT_SERVER_CONFIG_PATH: "${HOME}/.config/hilbert-server-cache/" # where to keep sync'ed content
```

I don't agree with specifying a URL for syncing. Syncing is a feature that is very specific to one installation and I assume that it will hardly be used anywhere else. If you just provide a URL, you will end up mirroring whats stored under this URL and then put logic into hilbert that converts the mirrored data into something useful (for hilbert and the rest of the host system), e.g. hilbert might upload application container images into the docker registry, copy its own and system config files here and there. If I remember correctly, in this particular installation, they want to sync everything to the management server that is not part of the initial setup by sys-admins. But that is clearly out of the scope of hilbert. Customer specific code paths should not be part of general hilbert. That is why I proposed https://github.com/hilbert/hilbert-cli/issues/29#issue-185078141: IT admins put a customer specific sync script into the config and hilbert will just execute this when `hilbert sync` is called. The script is responsible to leave a valid hilbert config behind after it exits (being with exit code 0 or != 0). If it breaks something or opens a security vulnerability, it is IT admins fault not ours.

**Comment by malex984** [comment]
@porst17 Ok, i see. I am sorry for such a long confusion on my part! Unfortunately i was considering the synchronization to be an integral part of Hilbert-CLI-Server, that would enable totally automatic server recovery from a clean state (e.g. after complete server wipe-out or replacement)...

For now we can rely on some location (e.g. specified by `${HILBERT_SERVER_CONFIG_PATH}`) on the server to contain the General YAML configuration with dependencies. That location  (`${HILBERT_SERVER_CONFIG_PATH}`) will be mounted into the management container as its persistent storage.

**Next** we may just add a **self-contained** and **standalone** script to synchronize `${HILBERT_SERVER_CONFIG_PATH}` with some fixed external location (like CMS).

**Comment by porst17** [comment]
The `sync` feature can still enable totally automatic server recovery. But the main difference is that the logic to actually do the recovery is not part of hilbert. The recovery is specific for each installation of hilbert. Other museums will not have the same type of CMS our current client has. The data may be kept in totally different locations and formats (e.g. they might have a second docker registry that is accessible from the outside and we have to sync to our internal one or whatever).

To summarize: Syncing will be part of the project we working on with our clients. But the specific way the syncing works is not part of hilbert itself aka separation of concerns.

**Comment by malex984** [comment]
I propose to require an external self-contained standalone script to be located in `${HILBERT_SERVER_CONFIG_PATH}`. It may just sync the contents of its `basedir` with some hard-coded external source via some hard-coded protocol/access (possibly updating the script itself). The exit return codes should be according to our rules.

Its name may be configurable in Hilbert.YAML via some variables (e.g. `hilbert_server_sync_script`) for the Server, in which case `Hilbert-CLI-Server` will be able to simply run it on request from the Dashboard's back-end. 

But I am not sure about who should update the server's docker registry with new docker images: that **external** script may not know how to do that...

**Comment by elondaits** [comment]
> I propose to require an external self-contained standalone script to be located in ${HILBERT_SERVER_CONFIG_PATH}

Just a side not, but: security-wise you shouldn't mix directories for data files with directories for executables. And design-wise it's better not to mix directories with static files that are part of the distribution (e.g. code and assets) and directories with files that can change and that are server specific and should be backed up (config, dbs, etc).

> Its name may be configurable in Hilbert.YAML via some variables (e.g. hilbert_server_sync_script) for the Server, in which case Hilbert-CLI-Server will be able to simply run it on request from the Dashboard's back-end.

The fact that syncing is out of the scope of hilbert means hilbert doesn't know anything about the script, nor its existance. If you add a key for the script in the config it means hilbert knows of the script.

I say we worry about that later, because it's add-on functionality. If it has to be launched through the UI I can simply add the ability to launch configurable user scripts from the dashboard for whatever purpose. That wouldn't involve the CLI at all unless the script itself calls it.

**Comment by porst17** [comment]
OK, let's declare this as out-of-scope for know. I will remove this issue from the cli design milestone. We will pick it up later when we actually start implementing it. It looks like a backwards compatible addition to me.

**Comment by porst17** [comment]
> I say we worry about that later, because it's add-on functionality. If it has to be launched through the UI I can simply add the ability to launch configurable user scripts from the dashboard for whatever purpose. That wouldn't involve the CLI at all unless the script itself calls it.

The possibility of calling general user defined script seems to be a good solution for functionality that is currently **out-of-scope** of hilbert. It could still be part of the CLI just like you can add user defined functionality to e.g. `git` via git aliases. This would allow admins to do hilbert-related work using the global hilbert CLI via ssh without having to rely on the UI and without worrying to much about script locations and the like.

The implementation in the cli and the config could also be very similar to [git aliases](https://git-scm.com/book/it/v2/Git-Basics-Git-Aliases), i.e. aliases can be used to provide shortcuts for frequently used hilbert subcommand and to run external commands via the `!` notation (this would be how the sync script would be called).

I can think of many ways to extend this mechanism to support really fancy stuff using parameter replacement etc. But we should only implement further extensions upon request or if we need it ourselves.

I think it is clear now that syncing will not directly be implemented in hilbert. Therefore, I am closing this now.
