### ISSUE TITLE
Configuration Design: configuration preset

### ISSUE THREAD

**Issue by malex984** [hilbert/hilbert-cli#30]
# We have to answer the following questions:
- [ ] what exactly configuration **preset** is?
- [ ] how to configure it?
- [ ] Does Dashboard applies **preset** to the current general configuration? 
- [ ] where to look for available presets?

My proposal was to switch between global `Stations`-like tables (e.g. https://gist.github.com/malex984/59d2b62c5098eb1005100f9249719505#file-preset_testgui-v0-1-0-yml)

@elondaits mentioned in the design draft (google document):

> Presets should only include the part of the configuration you'd be able to change from the front end: 
> app assignment to each station.
> Consider the system's cfg has two different parts:
> - Info we need to connect and interact with the stations (e.g. ip, ssh user). This changes if the IT department wants to modify infrastructure, add computers, etc.
> - Info on what to do (e.g what app to run on each station). This changes based on exhibitions, audience, day of the week, etc.
>   Presets should be discussed separately because they're a future separate feature anyway.

Note: this is a part of super-issue "Configuration Design": hilbert/hilbert-cli#13

**Comment by elondaits** [comment]
This was a feature for phase 2... I think we should first go from the current prototype to a solid phase 1 release and then worry about this extra feature.

**Comment by malex984** [comment]
@elondaits Ok, i agree with you in the case when presets are **not part of the general configuration** and **exist for the Dashboard only**.

**Comment by malex984** [comment]
For completeness:

In (#21)  @porst17 suggested to remove `default_application` from `Station` definition and put them to **presets** instead (later on). 

The consequence is the need for `Hilbert-CLI-Server` to deal with presets in order to regenerate individual station configs depending on a preset (and deploy them).

@malex984 outlined 2 possible ways to make presets accessible for `Hilbert-CLI-Server` tool in https://github.com/hilbert/hilbert-cli/issues/21#issuecomment-257295793

**Update**: it seems that **presets** may provide a convenient way to simultaneously change defaults of multiple stations in one go, for example by extending corresponding `Station::settings`'s fields (individually for any station requiring such a change). 
Use cases for such a concept would include, for instance:
- change `hilbert_station_default_application` to start a different compatible application upon booting (e.g. `hw_test_app` for HW testing on all stations)
- set `HILBERT_PREFERRED_LANGUAGE` to `english`, e.g. for some **International** event or meeting
  - enable verbosity or debug outputs from `Hilbert-CLI-Station` / Services / Applications
  - etc...

**Comment by malex984** [comment]
looks like this matter currently have almost nothing to do with hilbert-cli. 
@elondaits do you have another issue/task instead of this issue. 
@porst17 this one can probably be closed right away...

**Comment by porst17** [comment]
I agree that presets are a separate feature. I am also OK with implementing preset as a dashboard feature for now but in a later version I'd recommend to expose a cli for that as well. This means that the cli and the dashboard would share the same preset configuration.

I'll close this for now and we may reopen it later if appropriate.

**Comment by elondaits** [comment]
@porst17 remember that we have two CLIs now... Alex's low level CLI (this repository) and the hilbert-ui cli that I provided for MiMa. Since the UI is the main tracker of state for the whole system it requires all user actions to be taken from within that layer, and control access to the low level CLI.

... That mess is the reason two CLIs are needed.

... But I could easily add a command to activate presets from the UI CLI.

**Comment by porst17** [comment]
That's what I am saying (indirectly). The UI is not just a UI, but also a state tracker and IMO it would be better if the UI would just be a UI with a separate layer underneath that tracks state, errors, locks etc. But this is a bigger architectural change and shouldn't be discussed here.
