### ISSUE TITLE
Support of aliases for subcommands and external scripts

### ISSUE THREAD

**Issue by porst17** [hilbert/hilbert-cli#33]
In order to provide shorthands for frequently used command and the possibility to call external hilbert-related scripts via the CLI, hilbert should support user-defined aliases in the config that are exposed via the CLI.

The idea of aliases came up in the discussion of hilbert/hilbert-cli#29 in order to support the synchronization of externally hosting configuration files and application bundles to the hilbert management server.

Implementation and further discussion should start when the need for calling external scripts actually arises, i.e. not now but later.

---
TODO:
- [ ] find out how git aliases are defined exactly and what makes sense to implement

**Comment by porst17** [comment]
Implementation should be similar to [git aliases](https://git-scm.com/book/it/v2/Git-Basics-Git-Aliases), i.e. simple yet powerful: `!` to call external scripts and `-` resp. `--` for appending CLI parameters.

**Comment by malex984** [comment]
Do you mean to add them to our general configuration file (`Hilbert.yaml`) analogously to `~/.gitconfig`?

For example:

```
Aliases:
  au: "add -u"
  gv: "!f(){echo 'digraph git {';git log --pretty='format:  %h -> { %p }' \"$@\"|sed 's/[0-9a-f][0-9a-f]*/\"&\"/g'; echo '}';};f"
```

**Comment by porst17** [comment]
Exactly.

**Comment by malex984** [comment]
Ok, that will work for the server tool (`Hilbert-CLI-Server` )... What about the client tool `Hilbert-CLI-Station`?

**Comment by porst17** [comment]
I am only talking about `Hilbert-CLI-Server`, sorry for being imprecise.

**Comment by malex984** [comment]
@porst17 no such support yet

**Comment by porst17** [comment]
Solution: Use external wrapper scripts (and `hilbert cfg_query`). See also #59 and #64.
