### ISSUE TITLE
Configuration Validator: complex general validation

### ISSUE THREAD

**Issue by malex984** [hilbert/hilbert-cli#37]
**@elondaits commented on [hilbert-cli-config.py](https://github.com/hilbert/hilbert-cli/blob/feature/config_validate/config/hilbert-cli-config.py)**:
> Try not to do any complex general validation because if the UI starts 100 stations it'll call the CLI 100 times, and the configuration will be validated 100 times. So try to do any complex validation of structure only when it's needed. E.g. if someone asks to stop a station we don't need to check that station groups are compatible with assigned apps or anything.

**Comment by malex984** [comment]
Ok, this is where `hilbert-cli-config` is different from `hilbert-cli-server`.
IMO user should be able to **completely** verify their configuration before sharing/using it.

I imagine `hilbert-cli-config` will verify/parse the config as deep as possible (but depending on its switches it may skip some things to check, e.g. check for a proper ssh alias within ~/.ssh/config).
Then it may generate/serialize/cache the valid parsed result for `hilbert-cli-server`, which will not need to do any verification at all...
Also this `hilbert-cli-config` should generate individual station configs (e.g. something like the current directory `STATIONS/`), which will be deployed to stations (by hilbert's server part: `hilbert-cli-server`) to be used by the hilbert's client part (`hilbert-cli-station`).

It should only be done once upon configuration update.

This is what i started explaining with in "Configuration Flow", see: https://github.com/hilbert/hilbert-cli/blob/devel/docs/mng.png (or corresponding section of the Design Google Doc.)

Note: this may be part of General Hilbert design, for instance: (#14)

**Comment by malex984** [comment]
**@elondaits reply:**

> OK. Validating the whole config with a tool is perhaps useful. But you still need to validate the config in `hilbert-cli-server` when you're using it... if a value you require is missing, or is the wrong type, you must still throw an exception / error. That's where I would just leave each component to validate whatever it needs to use.

**Comment by malex984** [comment]
Currently no complex (time-consuming) validation is required by default. But in `PEDANTIC` mode all possible checks must be passed. Some checks require external scripts/tools or try to communicate over network with a station thus possibly taking a while. 

Therefore: the pedantic verification `hilbert -p cfg_verify Hilbert.yml` may be performed only once for each new configuration available (e.g. after each synchronization). Additionally in case of a valid configuration it may be cached in a parsed form (`.data.pickle`) for later direct usage.

The usage of `hilbert` tool is completely up to Dashboard back-end.

**Comment by elondaits** [comment]
If the cfg is invalid and you don't compile it to .pickle I will still attempt to read it and we'll be working with two different cfgs (myself with the "bad" cfg, which might still parse and you with the old pickled one).

If you want to cache the cfg as .pickle you have to be very careful of sync problems. At the minimum delete the pickle whenever a new cfg is loaded, so if it exists it's exactly the same as the other one.
