### ISSUE TITLE
Do not redeploy on stations after configuration synchronization if nothing changed

### ISSUE THREAD

**Issue by porst17** [hilbert/hilbert-cli#51]
If the hilbert configuration is modified, it will be synchronized will all stations and the system will be restarted on all stations. However, the configuration change might not effect each station and if the configuration of a station didn't change, the station should continue running without interruption.

**Comment by malex984** [comment]
TODO: Keep currently selected application if possible
TODO: Add a way to force deployment

**Comment by malex984** [comment]
should be done by hilbert/hilbert-cli#73
