### ISSUE TITLE
Reject any command execution that might interfere with another  command currently  executed in parallel

### ISSUE THREAD

**Issue by porst17** [hilbert/hilbert-cli#55]
What happens if several `hilbert station` commands (targeting the same station) are executed in rapid succession or even in parallel? Same with any other `station` or `server` command I might not think of right now.

**Comment by malex984** [comment]
DONE: all configuration-depending commands will place a global execution lock!

Moreover due to further work on `hilbert-station` (recursive self-call) one will also be able to switch-off the locking.

**Comment by porst17** [comment]
Where are the locks stored? On the station or on the server? What does _global_ mean in this context?

For `hilbert-station`, you mean that the recursive call will not lock anything, right?

**Comment by malex984** [comment]
it is about running `hilbert-station` on some station. To prevent parallel execution it creates a lockfile on the system. It may be located in one of the following places:
/var/run/hilbert /var/run/lock/lockdev /run/lock/lockdev /var/run/lock /run/lock /var/run /run /tmp/,
depending on which one exists and write-able.

**Comment by porst17** [comment]
So I assume that `hilbert-station` return a non-zero exit status if it detects another lock. What does `hilbert` on the server do in such a case? Just report the error to the caller?

**Comment by malex984** [comment]
AFAIR `hilbert` on the server-side just gets the error exit code and returns an error in that case (possibly with a special exit code)

**Comment by porst17** [comment]
Is it possible that the lock stays unreleased in case of a crash of `hilbert-station`? Is there a well-defined way to clean it up (i.e. for `hilbert` on the server and therefore also for `hilbert-ui`)?

**Comment by porst17** [comment]
I just noticed that @malex984 didn't answer [my question](https://github.com/hilbert/hilbert-cli/issues/55#issuecomment-358712959).
