### ISSUE TITLE
The subcommand parser should reject duplicate subcommand

### ISSUE THREAD

**Issue by porst17** [hilbert/hilbert-cli#68]
In #64, I overlooked the existing implemetation of the `cfg_query` subcommand and just added a second one with the same name. The subcommand parser didn't tell me about it, but it definitely should.

**Comment by malex984** [comment]
should be fixed with https://github.com/hilbert/hilbert-cli/commit/efe2924d921700ef6482d1d8f4c795a0bcff2158
